name: Generate Infrastructure
run-name: Generate Infrastructure with ${{ inputs.S3_CloudFront && 'S3_CloudFront' || '' }} ${{ inputs.Network && 'Network' || '' }} ${{ inputs.EKS_Config && 'EKS_Config' || '' }} ${{ inputs.EKS && 'EKS' || '' }}

on:
  workflow_dispatch:
    inputs:
      S3_CloudFront:
        description: 'Include S3_CloudFront module'
        required: false
        default: false
        type: boolean
      Network:
        description: 'Include Network module'
        required: false
        default: false
        type: boolean
      EKS_Config:
        description: 'Include EKS_Config module'
        required: false
        default: false
        type: boolean
      EKS:
        description: 'Include EKS module'
        required: false
        default: false
        type: boolean
      aws_account_id:
        description: 'AWS Account ID'
        required: true
        type: string
      project_name:
        description: 'Project Name'
        required: true
        type: string
      managed_by:
        description: 'Managed By'
        required: true
        type: string
      aws_region:
        description: 'AWS Region'
        required: true
        type: string
      vpc_cidr_range:
        description: 'VPC CIDR Range'
        required: true
        type: string
      cluster_name:
        description: 'Cluster Name'
        required: true
        type: string
      cluster_version:
        description: 'Cluster Version'
        required: true
        type: string
      eks_instance_type:
        description: 'EKS Instance Type'
        required: true
        type: string
      domain_name:
        description: 'Domain Name'
        required: true
        type: string

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Create values.json
      run: |
        echo '{
          "aws_account_id": "${{ inputs.aws_account_id }}",
          "project_name": "${{ inputs.project_name }}",
          "managed_by": "${{ inputs.managed_by }}",
          "aws_region": "${{ inputs.aws_region }}",
          "vpc_cidr_range": "${{ inputs.vpc_cidr_range }}",
          "cluster_name": "${{ inputs.cluster_name }}",
          "cluster_version": "${{ inputs.cluster_version }}",
          "eks_instance_type": "${{ inputs.eks_instance_type }}",
          "domain_name": "${{ inputs.domain_name }}"
        }' > values.json

    - name: cat values.json
      run: cat values.json
    - name: Run replace_vars.py
      run: |
        python replace_vars.py . values.json

    - name: Run generate_infra.py
      run: |
        python generate_infra.py ${{ inputs.S3_CloudFront }} ${{ inputs.Network }} ${{ inputs.EKS_Config }} ${{ inputs.EKS }}

    - name: Upload infrastructure directory
      uses: actions/upload-artifact@v4
      with:
        name: infrastructure
        path: infrastructure/
        retention-days: 1